# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.
# You can safely delete this file if you don't need it.
etcd-name = "default"
etcd-data-dir = "/var/lib/etcd"

etcd-client-end = 2379
etcd-server-end = 2380

etcd-listen-client-urls = "http://0.0.0.0:2379"
etcd-listen-peer-urls = "http://0.0.0.0:2380"
etcd-advertise-client-urls = "http://0.0.0.0:2379"
etcd-advertise-peer-urls = "http://0.0.0.0:2380"
