#!/bin/bash

exec 2>&1

# Copy the nginx config into position
cp -r {{pkg.svc_config_path}}/nginx.conf \
      {{pkgPathFor "core/nginx"}}/config/nginx.conf

# Copy the php-fom config into position
cp -n {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf.default \
      {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf

hab service load core/nginx --group {{svc.group}} --force
