##################### CrateDB Configuration ########################
#
# Notes: https://crate.io/docs/reference/en/1.1.2/configuration.html
#
####################################################################

# If this Habitat supervisor is leader
# Set this Crate node to be leader, too

{{#if svc.me.leader ~}}
  node.master: true
{{else ~}}
  node.master: false
{{/if ~}}

# Port setup

http.port: {{cfg.port.http}}
transport.tcp.port: {{cfg.port.tcp}}
psql.port: {{cfg.port.postgres}}

# Paths

path.data: {{pkg.svc_var_path}}/data
path.work: {{pkg.svc_var_path}}/work
path.logs: {{pkg.svc_var_path}}/logs
path.repo: {{cfg.path.repo}}

## Discovery: Unicast Host Discovery

discovery.zen.ping.unicast.hosts:
{{#each svc.members ~}}
  - {{sys.ip}}
{{/each}}

## Metadata: Gateway

gateway.expected_nodes: {{cfg.gateway.expected_nodes}}
gateway.recover_after_time: {{cfg.gateway.recover_after_time}}
gateway.recover_after_nodes: {{cfg.gateway.recover_after_nodes}}
