[jenkins]
  winstone_opts = "-XX:PermSize=512M -XX:MaxPermSize=2048M -Xmn128M -Xms1024M -Xmx2048M"

  [jenkins.https] 
    port = 443
    listen_address = "0.0.0.0"
    certificate = ""
    private_key = ""

  [jenkins.ajp13]
    port = -1

[java]
  opts = ""